/**
 * Argon2id parameters used to derive MasterKey = Argon2id(password, kdf_salt,
 * kdf_params), per repo CLAUDE.md Resolved Design Decision #1.
 *
 * Field names and DEFAULT value mirror the Android client's
 * `android/app/src/main/java/id/quezacolt/veilkeeper/crypto/KdfParams.kt`
 * exactly (which itself mirrors the backend's `KDFParams` struct /
 * `kdf_params` wire JSON) -- this is deliberate, not a coincidence: Web must
 * be able to derive the identical MasterKey for an existing account whose
 * kdf_params were generated by (or for) the Android client. Do not change
 * DEFAULT here without also changing it in KdfParams.kt and understanding
 * the cross-platform implications.
 */
export interface KdfParams {
  memoryKiB: number
  iterations: number
  parallelism: number
}

/**
 * Default parameters for a newly registered account: 64 MiB memory, 3
 * iterations, 4-way parallelism -- exactly `KdfParams.DEFAULT` on Android.
 */
export const DEFAULT_KDF_PARAMS: KdfParams = {
  memoryKiB: 64 * 1024,
  iterations: 3,
  parallelism: 4,
}

export const CURRENT_KDF_VERSION = 1
